config/routes.rb
Rails.application.routes.draw do

  get 'guest/result'

  root 'pages#top'

  get  '/lotteries'      , to: 'lotteries#show'
  get  '/lotteries/deal' , to: 'pages#deal'
  get  '/lotteries/draw' , to: 'lotteries#draw'
  get  '/q_deal_tickets' , to: 'tickets#quick_deal'
  post '/deal_tickets'   , to: 'tickets#deal'

  # ゲスト画面
  get '/entry/:guest_code/:token' , to: 'guest#entry'
  get '/guest/:guest_code/:token' , to: 'guest#open_lottery' , as: :guest
  get '/guest/result'             , to: 'guest#result'

  resources :owners
  resources :lotteries, param: :code
  resources :gifts  #  , param: :seq
  resources :tickets

  ### 開発用画面 ###
  # キャッシュをいじる
  # https://simple-lottery-sano400jp.c9users.io/devpages/cacheedit
  get  'devpages/cacheedit', to:'devpages#cacheedit'
  get  'devpages/setcache', to:'devpages#setcache'

end

app/models/gift.rb
class Gift < ActiveRecord::Base
  # def to_param
  #   seq
  # end
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  before_action :set_gift, only: [:show, :edit, :update, :destroy]

  # GET /gifts
  # GET /gifts.json
  def index
    @lottery_code = session[:lottery_code]
    @gifts = Gift.where(lottery_code: @lottery_code)
    # @gifts = Gift.all
  end

  # GET /gifts/1
  # GET /gifts/1.json
  def show
  end

  # GET /gifts/new
  def new
    @gift = Gift.new
  end

  # GET /gifts/1/edit
  def edit
  end

  # POST /gifts
  # POST /gifts.json
  def create
    lottery_code = session[:lottery_code]
    max_seq = Gift.where(lottery_code: lottery_code).maximum(:seq)
    if max_seq.nil?
      max_seq = 0
    end

    @gift = Gift.new(gift_params)
    @gift.lottery_code = lottery_code
    @gift.seq = max_seq + 1

    respond_to do |format|
      if @gift.save
        format.html { redirect_to @gift, notice: 'Gift was successfully created.' }
        format.json { render :show, status: :created, location: @gift }
      else
        format.html { render :new }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gifts/1
  # PATCH/PUT /gifts/1.json
  def update
    respond_to do |format|
      if @gift.update(gift_params)
        format.html { redirect_to @gift, notice: 'Gift was successfully updated.' }
        format.json { render :show, status: :ok, location: @gift }
      else
        format.html { render :edit }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gifts/1
  # DELETE /gifts/1.json
  def destroy
    @gift.destroy
    respond_to do |format|
      format.html { redirect_to gifts_url, notice: 'Gift was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gift
      @gift = Gift.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gift_params
      params.require(:gift).permit(:lottery_code, :name, :start_cnt, :delived_cnt, :image_l_url, :image_m_url, :image_s_url)
    end
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/views/gifts/_form.html.erb
<%= form_for(@gift) do |f| %>
  <% if @gift.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gift.errors.count, "error") %> prohibited this gift from being saved:</h2>

      <ul>
      <% @gift.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lottery_code %><br>
    <%= f.text_field :lottery_code %>
  </div>
  <div class="field">
    <%= f.label :seq %><br>
    <%= f.text_field :seq %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :start_cnt %><br>
    <%= f.number_field :start_cnt %>
  </div>
  <div class="field">
    <%= f.label :image_l_url %><br>
    <%= f.text_field :image_l_url %>
  </div>
  <div class="field">
    <%= f.label :image_m_url %><br>
    <%= f.text_field :image_m_url %>
  </div>
  <div class="field">
    <%= f.label :image_s_url %><br>
    <%= f.text_field :image_s_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gifts/_form_new.html.erb
<%= form_for(@gift) do |f| %>
  <% if @gift.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gift.errors.count, "error") %> prohibited this gift from being saved:</h2>

      <ul>
      <% @gift.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :start_cnt %><br>
    <%= f.number_field :start_cnt %>
  </div>
  <div class="field">
    <%= f.label :image_l_url %><br>
    <%= f.text_field :image_l_url %>
  </div>
  <div class="field">
    <%= f.label :image_m_url %><br>
    <%= f.text_field :image_m_url %>
  </div>
  <div class="field">
    <%= f.label :image_s_url %><br>
    <%= f.text_field :image_s_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gifts/edit.html.erb
<h1>Editing Gift</h1>

<%= render 'form' %>

<%= link_to 'Show', @gift %> |
<%= link_to 'Back', gifts_path %>

app/views/gifts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Gifts</h1>
<%= @lottery_code %>
<table>
  <thead>
    <tr>
      <th>Lottery code</th>
      <th>seq</th>
      <th>Name</th>
      <th>Start cnt</th>
      <th>Image l url</th>
      <th>Image m url</th>
      <th>Image s url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gifts.each do |gift| %>
      <tr>
        <td><%= gift.lottery_code %></td>
        <td><%= gift.seq %></td>
        <td><%= gift.name %></td>
        <td><%= gift.start_cnt %></td>
        <td><%= gift.image_l_url %></td>
        <td><%= gift.image_m_url %></td>
        <td><%= gift.image_s_url %></td>
        <td><%= link_to 'Show', gift %></td>
        <td><%= link_to 'Edit', edit_gift_path(gift) %></td>
        <td><%= link_to 'Destroy', gift, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gift', new_gift_path %>

app/views/gifts/new.html.erb
<h1>New Gift</h1>

<%= render 'form_new' %>

<%= link_to 'Back', gifts_path %>

app/views/gifts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lottery code:</strong>
  <%= @gift.lottery_code %>
</p>

<p>
  <strong>Seq:</strong>
  <%= @gift.seq %>
</p>

<p>
  <strong>Name:</strong>
  <%= @gift.name %>
</p>

<p>
  <strong>Start cnt:</strong>
  <%= @gift.start_cnt %>
</p>

<p>
  <strong>Image l url:</strong>
  <%= @gift.image_l_url %>
</p>

<p>
  <strong>Image m url:</strong>
  <%= @gift.image_m_url %>
</p>

<p>
  <strong>Image s url:</strong>
  <%= @gift.image_s_url %>
</p>

<%= link_to 'Edit', edit_gift_path(@gift) %> |
<%= link_to 'Back', gifts_path %>