config/routes.rb
Rails.application.routes.draw do

  get 'guest/result'

  root 'pages#top'

  get  '/lotteries'      , to: 'lotteries#show'
  get  '/lotteries/deal' , to: 'pages#deal'
  get  '/lotteries/draw' , to: 'lotteries#draw'
  get  '/q_deal_tickets' , to: 'tickets#quick_deal'
  post '/deal_tickets'   , to: 'tickets#deal'

  # ゲスト画面
  get '/entry/:guest_code/:token' , to: 'guest#entry'
  get '/guest/:guest_code/:token' , to: 'guest#open_lottery' , as: :guest
  get '/guest/result'             , to: 'guest#result'

  resources :owners
  resources :lotteries, param: :code
  resources :gifts  #  , param: :seq
  resources :tickets

  ### 開発用画面 ###
  # キャッシュをいじる
  # https://simple-lottery-sano400jp.c9users.io/devpages/cacheedit
  get  'devpages/cacheedit', to:'devpages#cacheedit'
  get  'devpages/setcache', to:'devpages#setcache'

end

app/models/lottery.rb
class Lottery < ActiveRecord::Base
  def to_param
    code
  end
end

app/controllers/lotteries_controller.rb
require "securerandom"

class LotteriesController < ApplicationController
  before_action :set_lottery, only: [:show, :edit, :update, :destroy]

  # GET /lotteries
  # GET /lotteries.json
  def index
    @lotteries = Lottery.all
  end

  # GET /lotteries/1
  # GET /lotteries/1.json
  def show
  end

  # GET /lotteries/new
  def new
    @lottery = Lottery.new
    @lottery.owner_code = session[:owner_code]
  end

  # GET /lotteries/1/edit
  def edit
  end

  # POST /lotteries
  # POST /lotteries.json
  def create
    @lottery = Lottery.new(lottery_params)
    @lottery.owner_code = session[:owner_code]

    # lottery_codeの作成
    strToken = ""
    iStop = 0
    loop{
      iStop = iStop + 1
      strToken = SecureRandom.hex(20)
      if Lottery.where(code: strToken).blank?
        break
      end
      if iStop > 100 then
        strToken = "hoge"
        break
      end
    }
    @lottery.code = strToken

    # guest_codeの作成
    str_guest_code = "huga"
    iStop = 0
    loop{
      iStop = iStop + 1
      str_guest_code = SecureRandom.hex(10)
      if Lottery.where(guest_code: str_guest_code).blank?
        break
      end
      if iStop > 100 then
        str_guest_code = "hoge"
        break
      end
    }
    @lottery.guest_code = str_guest_code

    respond_to do |format|
      if @lottery.save
        format.html { redirect_to edit_lottery_path(@lottery) }
#        format.json { render :show, status: :created, location: @lottery }
        session[:lottery_code] = @lottery.code
      else
        format.html { render :new }
        format.json { render json: @lottery.errors, status: :unprocessable_entity }
      end
    end
  end

  ### 抽選実行ボタン
  def draw
    # 抽選実行処理起動（本体はヘルパー使うべきか？）
    run_draw
  end

  def run_draw
    # Giftsからコードと個数
    # giftsList = Gift.find_by(lottery_code: session[:lottery_code])

    # Gifts毎繰り返し
    Gift.where(lottery_code: session[:lottery_code]).find_each do |gift|
      seq = gift.seq
      cnt = gift.start_cnt

      # 景品の残り個数を取得
      rem_cnt = cnt - Ticket.where(lottery_code: session[:lottery_code], gift_seq: seq).count

      # ランダムで配列のindexを選ぶ
      winningTickets = Ticket.where(lottery_code: session[:lottery_code], status: "1").order("RANDOM()").limit(rem_cnt)

      if winningTickets.count == 0 then
      else
        # 当選配列のTickets.gift_seq（項目名後悔中。gift_codeにすべきだったか、、、）を更新
        winningTickets.each do |wt|
          wt.gift_seq = seq
        end
        winningTickets.update_all("gift_seq = " + seq.to_s + ", status = '2'")
      end
    end
  end
  
  # PATCH/PUT /lotteries/1
  # PATCH/PUT /lotteries/1.json
  def update
    respond_to do |format|
      if @lottery.update(lottery_params)
        format.html { redirect_to @lottery, notice: 'Lottery was successfully updated.' }
        format.json { render :show, status: :ok, location: @lottery }
      else
        format.html { render :edit }
        format.json { render json: @lottery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lotteries/1
  # DELETE /lotteries/1.json
  def destroy
    @lottery.destroy
    respond_to do |format|
      format.html { redirect_to lotteries_url, notice: 'Lottery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lottery
      @lottery = Lottery.find_by(code: params[:code])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lottery_params
      params.require(:lottery).permit(:code, :owner_code, :title, :draw_time, :redraw_range, :nonres_redraw, :end_time, :gest_code)
    end
end

app/helpers/lotteries_helper.rb
module LotteriesHelper
end

app/views/lotteries/_form.html.erb
<%= form_for(@lottery) do |f| %>
  <% if @lottery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lottery.errors.count, "error") %> prohibited this lottery from being saved:</h2>

      <ul>
      <% @lottery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :owner_code %><br>
    <%= f.text_field :owner_code %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :draw_time %><br>
    <%= f.datetime_select :draw_time %>
  </div>
  <div class="field">
    <%= f.label :redraw_range %><br>
    <%= f.number_field :redraw_range %>
  </div>
  <div class="field">
    <%= f.label :nonres_redraw %><br>
    <%= f.check_box :nonres_redraw %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.datetime_select :end_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lotteries/_form_home.html.erb
<%= form_for(@lottery) do |f| %>
  <% if @lottery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lottery.errors.count, "error") %> prohibited this lottery from being saved:</h2>

      <ul>
      <% @lottery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :draw_time %><br>
    <%= f.datetime_select :draw_time %>
  </div>
<% if false %>
  <div class="field">
    <%= f.label :redraw_range %><br>
    <%= f.number_field :redraw_range %>
  </div>
  <div class="field">
    <%= f.label :nonres_redraw %><br>
    <%= f.check_box :nonres_redraw %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.datetime_select :end_time %>
  </div>
<% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lotteries/_form_new.html.erb
<%= form_for(@lottery) do |f| %>
  <% if @lottery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lottery.errors.count, "error") %> prohibited this lottery from being saved:</h2>

      <ul>
      <% @lottery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :owner_code %><br>
    <%= @lottery.owner_code %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/lotteries/draw.html.erb
抽選した。</br>

app/views/lotteries/edit.html.erb
<h1>Title:<%= @lottery.title %></h1>

<%= render 'form_home' %>

<%= link_to 'Gifts', gifts_path %><br>
<%= link_to 'Deal' , lotteries_deal_path %><br>
<%= link_to 'Draw' , lotteries_draw_path %><br>
<br>
<%= link_to 'Show', @lottery %>
<%= link_to 'Back', lotteries_path %>

app/views/lotteries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Lotteries</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Owner code</th>
      <th>Title</th>
      <th>Draw time</th>
      <th>Redraw range</th>
      <th>Nonres redraw</th>
      <th>End time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lotteries.each do |lottery| %>
      <tr>
        <td><%= lottery.code %></td>
        <td><%= lottery.owner_code %></td>
        <td><%= lottery.title %></td>
        <td><%= lottery.draw_time %></td>
<% if false %>
        <td><%= lottery.redraw_range %></td>
        <td><%= lottery.nonres_redraw %></td>
        <td><%= lottery.end_time %></td>
<% end %>
        <td><%= link_to 'Show', lottery %></td>
        <td><%= link_to 'Edit', edit_lottery_path(lottery) %></td>
        <td><%= link_to 'Destroy', lottery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lottery', new_lottery_path %>

app/views/lotteries/new.html.erb
<h1>New Lottery</h1>

<%= render 'form_new' %>

<%= link_to 'Back', lotteries_path %>

app/views/lotteries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @lottery.code %>
</p>
<p>
  <strong>Owner code:</strong>
  <%= @lottery.owner_code %>
</p>
<p>
  <strong>Guest code:</strong>
  <%= @lottery.guest_code %>
</p>

<p>
  <strong>Title:</strong>
  <%= @lottery.title %>
</p>

<p>
  <strong>Draw time:</strong>
  <%= @lottery.draw_time %>
</p>

<p>
  <strong>Redraw range:</strong>
  <%= @lottery.redraw_range %>
</p>

<p>
  <strong>Nonres redraw:</strong>
  <%= @lottery.nonres_redraw %>
</p>

<p>
  <strong>End time:</strong>
  <%= @lottery.end_time %>
</p>

<%= link_to 'Edit', edit_lottery_path(@lottery) %> |
<%= link_to 'Back', lotteries_path %>