config/routes.rb
Rails.application.routes.draw do

  get 'guest/result'

  root 'pages#top'

  get  '/lotteries'      , to: 'lotteries#show'
  get  '/lotteries/deal' , to: 'pages#deal'
  get  '/lotteries/draw' , to: 'lotteries#draw'
  get  '/q_deal_tickets' , to: 'tickets#quick_deal'
  post '/deal_tickets'   , to: 'tickets#deal'

  # ゲスト画面
  get '/entry/:guest_code/:token' , to: 'guest#entry'
  get '/guest/:guest_code/:token' , to: 'guest#open_lottery' , as: :guest
  get '/guest/result'             , to: 'guest#result'

  resources :owners
  resources :lotteries, param: :code
  resources :gifts  #  , param: :seq
  resources :tickets

  ### 開発用画面 ###
  # キャッシュをいじる
  # https://simple-lottery-sano400jp.c9users.io/devpages/cacheedit
  get  'devpages/cacheedit', to:'devpages#cacheedit'
  get  'devpages/setcache', to:'devpages#setcache'

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
end

app/controllers/tickets_controller.rb
require "securerandom"
require "rubygems"
require "rqrcode"
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

#############################################
  def deal
    @deal_cnt = params['deal_cnt'].to_i
    lottery_code = session[:lottery_code]

    # seqの最大値を取得
    max_seq = Ticket.where(lottery_code: lottery_code).maximum(:seq)
    if max_seq.nil?
      max_seq = 0
    end

    ### くじ情報取得
    rec_lottery = Lottery.find_by(code: lottery_code)
    guest_code = rec_lottery.guest_code

    # 繰り返し登録処理実行
    @deal_cnt.times do
      ### 登録値設定
      max_seq = max_seq + 1
      new_ticket = Ticket.new
      new_ticket.lottery_code = lottery_code
      new_ticket.guest_code = guest_code
      new_ticket.seq = max_seq
      # テーブルを検索して結果が0になるまで繰り返し実行
      strToken = ""
      iStop = 0
      loop{
        iStop = iStop + 1
        strToken = SecureRandom.hex(4)
        if Ticket.where(lottery_code: lottery_code, token: strToken).blank?
          break
        end
        if iStop > 100 then
          strToken = "hoge"
          break
        end
      }
      new_ticket.token = strToken
      if new_ticket.save
      else
      end
    end
  end

#############################################
  def quick_deal

    lottery_code = session[:lottery_code]
    ### レコード取得
    # seqの最大値を取得
    max_seq = Ticket.where(lottery_code: lottery_code).maximum(:seq)
    if max_seq.nil?
      max_seq = 0
    end
    max_seq = max_seq + 1 #次のseq

    ### くじ情報取得
    rec_lottery = Lottery.find_by(code: lottery_code)
    guest_code = rec_lottery.guest_code

    ### 登録値設定
    new_ticket = Ticket.new
    new_ticket.lottery_code = lottery_code
    new_ticket.guest_code = guest_code
    new_ticket.seq = max_seq

    # 一意のトークンを生成（テーブルを検索して結果が0になるまで繰り返し実行）
    strToken = ""
    iStop = 0
    loop{
      iStop = iStop + 1
      strToken = SecureRandom.hex(4)
      if Ticket.where(lottery_code: lottery_code, token: strToken).blank?
        break
      end
      if iStop > 100 then
        strToken = "hoge"
        break
      end
    }
    new_ticket.token = strToken
    if new_ticket.save
    else
    end

    # チケットのURLを作成
    @url_str = "https://simple-lottery-sano400jp.c9users.io/entry/" << guest_code << "/" << strToken
  end

#############################################
  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.where(lottery_code: session[:lottery_code])
  end

#############################################
  # GET /tickets/1
  # GET /tickets/1.json
  def show
    @url_str = "https://simple-lottery-sano400jp.c9users.io/entry/" << @ticket.guest_code << "/" << @ticket.token
  end

#############################################
  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

#############################################
  # GET /tickets/1/edit
  def edit
  end

#############################################
  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

#############################################
  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

#############################################
  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

#############################################
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:lottery_code, :seq, :token, :gift_seq, :act_flg, :status, :guest_code)
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= form_for(@ticket) do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lottery_code %><br>
    <%= f.text_field :lottery_code %>
  </div>
  <div class="field">
    <%= f.label :seq %><br>
    <%= f.number_field :seq %>
  </div>
  <div class="field">
    <%= f.label :token %><br>
    <%= f.text_field :token %>
  </div>
  <div class="field">
    <%= f.label :gift_seq %><br>
    <%= f.number_field :gift_seq %>
  </div>
  <div class="field">
    <%= f.label :act_flg %><br>
    <%= f.check_box :act_flg %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tickets/deal.html.erb
<%= @deal_cnt %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tickets</h1>

<table>
  <thead>
    <tr>
      <th>Lottery code</th>
      <th>Seq</th>
      <th>Token</th>
      <th>Gift seq</th>
      <th>Act flg</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.lottery_code %></td>
        <td><%= ticket.seq %></td>
        <td><%= ticket.token %></td>
        <td><%= ticket.gift_seq %></td>
        <td><%= ticket.act_flg %></td>
        <td><%= ticket.status %></td>
        <td><%= link_to 'Show', ticket %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
        <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form' %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/quick_deal.html.erb
URL:<%= @url_str %><br>
<%= qrcode_tag @url_str, module_size: 5 %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lottery code:</strong>
  <%= @ticket.lottery_code %>
</p>

<p>
  <strong>Seq:</strong>
  <%= @ticket.seq %>
</p>

<p>
  <strong>Token:</strong>
  <%= @ticket.token %>
</p>

<p>
  <strong>Gift seq:</strong>
  <%= @ticket.gift_seq %>
</p>

<p>
  <strong>Act flg:</strong>
  <%= @ticket.act_flg %>
</p>

<p>
  <strong>Status:</strong>
  <%= @ticket.status %>
</p>

<p>
  <strong>QR:</strong>
  <%= qrcode_tag @url_str, module_size: 5 %><br>
  <strong>URL:</strong><%= @url_str %>
</p>

<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>